### ISSUE TITLE
Error: Cannot find module 'bitcore-mnemonic'

### ISSUE THREAD

**Issue by ly95** [guantau/byteball-genesis#4]
运行 npm run init 报错

```
> byteball-genesis@1.0.0 init /Users/linyang/code/works/byteball-genesis
> npm --prefix genesis run init


> wallet-paying@1.0.0 init /Users/linyang/code/works/byteball-genesis/genesis
> node init.js

module.js:549
    throw err;
    ^

Error: Cannot find module 'bitcore-mnemonic'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

**Comment by guantau** [comment]
you should run "npm install" first

**Comment by ly95** [comment]
The steps are consistent with the README_zh.md. Does it support the Byteball latest version?

**Comment by guantau** [comment]
yes, I have update the codes
